site_name: Assigment 1 - Facebook Mock 
site_description: >-
  User Story 
site_url: https://mockfacebook.com/
site_author: Sophie Harrison
repo_url: https://github.com/acsharrison/comp3700
nav:
  - Home: index.md
  - User Cases:
    - User Case 1: usercase1.md
    - User Case 2: usercase2.md
these: readthedocs
markdown_extensions:
  - attr_list
  - md_in_html
